name: FTP Upload

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the upload on

jobs:
  ftp-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload code to FTP
        uses : SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: www/fiches-exos/ 
